import { MainCategory, SubCategory, NestedCategory, Product } from '../types';

export const MOCK_CATEGORIES: MainCategory[] = [
  { _id: 'cat1', nameAr: 'جهاز تتبع مركبات', nameEn: 'Vehicle Tracking Device', slug: 'vehicle-tracking' },
  { _id: 'cat2', nameAr: 'كاميرات ارمكو', nameEn: 'Aramco Cameras', slug: 'aramco-cameras' },
  { _id: 'cat3', nameAr: 'فلاش كام', nameEn: 'Flash Cam', slug: 'flash-cam' },
];

export const MOCK_SUBCATEGORIES: SubCategory[] = [
  // Subcategories for Category 1 (جهاز تتبع مركبات)
  { _id: 'sub1', fatherId: 'cat1', nameAr: 'شخصي', nameEn: 'Personal', slug: 'personal' },
  { _id: 'sub2', fatherId: 'cat1', nameAr: 'هيئة نقل تعليمي', nameEn: 'Educational Transport Authority', slug: 'educational-transport' },
  { _id: 'sub3', fatherId: 'cat1', nameAr: 'نقل متخصص', nameEn: 'Specialized Transport', slug: 'specialized-transport' },
  { _id: 'sub4', fatherId: 'cat1', nameAr: 'دراجات نارية', nameEn: 'Motorcycles', slug: 'motorcycles' },
  { _id: 'sub5', fatherId: 'cat1', nameAr: 'تعليمي', nameEn: 'Educational', slug: 'educational' },

  // Subcategories for Category 3 (فلاش كام)
  { _id: 'sub6', fatherId: 'cat3', nameAr: 'لايف', nameEn: 'Live', slug: 'live' },
  { _id: 'sub7', fatherId: 'cat3', nameAr: 'تسجيل', nameEn: 'Recording', slug: 'recording' },
];

export const MOCK_NESTED_CATEGORIES: NestedCategory[] = [
  // Nested categories for Subcategory 1 (شخصي)
  { _id: 'nested1', subCategoryId: 'sub1', nameAr: 'سلكي', nameEn: 'Wired', slug: 'wired' },
  { _id: 'nested2', subCategoryId: 'sub1', nameAr: 'لاسلكي', nameEn: 'Wireless', slug: 'wireless' },
  { _id: 'nested3', subCategoryId: 'sub1', nameAr: 'OBD', nameEn: 'OBD', slug: 'obd' },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    _id: 'prod1',
    name: 'GT06 Wired Tracker',
    nameAr: 'جهاز تتبع سلكي GT06',
    nameEn: 'GT06 Wired Tracker',
    category: 'cat1',
    subCategory: 'sub1',
    subSubCategory: 'nested1',
    brand: 'Brand',
    brandAr: 'علامة تجارية',
    brandEn: 'Brand',
    price: 100,
    costPrice: 80,
    discountPrice: 90,
    weight: 0.2,
    sku: 'TRK-001',
    maxQuantityPerCustomer: 5,
    subTitle: 'Accurate Vehicle Tracking',
    subTitleAr: 'تتبع دقيق للمركبات',
    subTitleEn: 'Accurate Vehicle Tracking',
    promoTitle: 'Best Seller',
    promoTitleAr: 'الأكثر مبيعاً',
    promoTitleEn: 'Best Seller',
    description: 'Advanced wired vehicle tracker supporting real-time alerts.',
    descriptionAr: 'جهاز تتبع مركبات سلكي متطور يدعم التنبيهات اللحظية.',
    descriptionEn: 'Advanced wired vehicle tracker supporting real-time alerts.',
    image: 'https://picsum.photos/seed/tracker1/400/400',
    seoTitle: 'GT06 Tracker',
    seoTitleAr: 'جهاز تتبع GT06',
    seoTitleEn: 'GT06 Tracker',
    seoUrl: 'gt06-tracker',
    seoDescription: 'Best wired vehicle tracker in Saudi Arabia',
    seoDescriptionAr: 'أفضل جهاز تتبع مركبات سلكي في السعودية',
    seoDescriptionEn: 'Best wired vehicle tracker in Saudi Arabia',
    requiresShipping: true,
    trackQuantity: true,
    channels: ['meta', 'google'],
    created_at: new Date().toISOString(),
  },
  {
    _id: 'prod2',
    name: 'Aramco Smart Camera',
    nameAr: 'كاميرا ارمكو الذكية',
    nameEn: 'Aramco Smart Camera',
    category: 'cat2',
    subCategory: '',
    subSubCategory: '',
    brand: 'Aramco',
    brandAr: 'ارمكو',
    brandEn: 'Aramco',
    price: 500,
    costPrice: 400,
    discountPrice: 450,
    weight: 1.5,
    sku: 'CAM-ARM-01',
    maxQuantityPerCustomer: 2,
    subTitle: 'High-Definition Monitoring',
    subTitleAr: 'مراقبة عالية الدقة',
    subTitleEn: 'High-Definition Monitoring',
    promoTitle: 'New',
    promoTitleAr: 'جديد',
    promoTitleEn: 'New',
    description: 'Security camera compliant with Aramco safety standards.',
    descriptionAr: 'كاميرا مراقبة متوافقة مع معايير ارمكو للأمن والسلامة.',
    descriptionEn: 'Security camera compliant with Aramco safety standards.',
    image: 'https://picsum.photos/seed/camera1/400/400',
    seoTitle: 'Aramco Camera',
    seoTitleAr: 'كاميرا ارمكو',
    seoTitleEn: 'Aramco Camera',
    seoUrl: 'aramco-camera',
    seoDescription: 'Aramco certified security cameras',
    seoDescriptionAr: 'كاميرات مراقبة معتمدة من ارمكو',
    seoDescriptionEn: 'Aramco certified security cameras',
    requiresShipping: true,
    trackQuantity: false,
    channels: ['meta', 'google', 'snapchat'],
    created_at: new Date().toISOString(),
  },
];
